var namespacegeodesk =
[
    [ "Box", "classgeodesk_1_1_box.html", "classgeodesk_1_1_box" ],
    [ "Coordinate", "classgeodesk_1_1_coordinate.html", "classgeodesk_1_1_coordinate" ],
    [ "CoordinateSpanIterator", "classgeodesk_1_1_coordinate_span_iterator.html", "classgeodesk_1_1_coordinate_span_iterator" ],
    [ "Feature", "classgeodesk_1_1_feature.html", "classgeodesk_1_1_feature" ],
    [ "FeaturePtr", "classgeodesk_1_1_feature_ptr.html", "classgeodesk_1_1_feature_ptr" ],
    [ "Features", "classgeodesk_1_1_features.html", "classgeodesk_1_1_features" ],
    [ "FixedLonLat", "classgeodesk_1_1_fixed_lon_lat.html", "classgeodesk_1_1_fixed_lon_lat" ],
    [ "Key", "classgeodesk_1_1_key.html", "classgeodesk_1_1_key" ],
    [ "KeySchema", "classgeodesk_1_1_key_schema.html", "classgeodesk_1_1_key_schema" ],
    [ "LeafletFormatter", "classgeodesk_1_1_leaflet_formatter.html", "classgeodesk_1_1_leaflet_formatter" ],
    [ "LeafletSettings", "structgeodesk_1_1_leaflet_settings.html", "structgeodesk_1_1_leaflet_settings" ],
    [ "LonLat", "classgeodesk_1_1_lon_lat.html", "classgeodesk_1_1_lon_lat" ],
    [ "MapWriter", "classgeodesk_1_1_map_writer.html", "classgeodesk_1_1_map_writer" ],
    [ "Mercator", "classgeodesk_1_1_mercator.html", "classgeodesk_1_1_mercator" ],
    [ "Node", "classgeodesk_1_1_node.html", "classgeodesk_1_1_node" ],
    [ "Nodes", "classgeodesk_1_1_nodes.html", "classgeodesk_1_1_nodes" ],
    [ "Polygonizer", "classgeodesk_1_1_polygonizer.html", "classgeodesk_1_1_polygonizer" ],
    [ "QueryException", "classgeodesk_1_1_query_exception.html", "classgeodesk_1_1_query_exception" ],
    [ "Relation", "classgeodesk_1_1_relation.html", "classgeodesk_1_1_relation" ],
    [ "Relations", "classgeodesk_1_1_relations.html", "classgeodesk_1_1_relations" ],
    [ "StringHolder", "classgeodesk_1_1_string_holder.html", "classgeodesk_1_1_string_holder" ],
    [ "StringValue", "classgeodesk_1_1_string_value.html", "classgeodesk_1_1_string_value" ],
    [ "Tag", "classgeodesk_1_1_tag.html", "classgeodesk_1_1_tag" ],
    [ "Tags", "classgeodesk_1_1_tags.html", "classgeodesk_1_1_tags" ],
    [ "TagValue", "classgeodesk_1_1_tag_value.html", "classgeodesk_1_1_tag_value" ],
    [ "Way", "classgeodesk_1_1_way.html", "classgeodesk_1_1_way" ],
    [ "Ways", "classgeodesk_1_1_ways.html", "classgeodesk_1_1_ways" ],
    [ "FeatureType", "namespacegeodesk.html#ab4c15802927accc42f5c68cd19e7c828", [
      [ "NODE", "namespacegeodesk.html#ab4c15802927accc42f5c68cd19e7c828a0cc25b606fe928a0c9a58f7f209c4495", null ],
      [ "WAY", "namespacegeodesk.html#ab4c15802927accc42f5c68cd19e7c828abeb410f25fbf2fdde0e664a4b6cb6f42", null ],
      [ "RELATION", "namespacegeodesk.html#ab4c15802927accc42f5c68cd19e7c828a597b1b050c9cf333a3f75f52eea33279", null ]
    ] ],
    [ "operator<<", "namespacegeodesk.html#adb91e057956b77a3eac7b25d89290739", null ],
    [ "typeName", "namespacegeodesk.html#ab86124bb3ebef6047b94353477a49143", null ]
];